# Generated by Django 3.2.5 on 2023-11-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
