# Generated by Django 3.2.5 on 2023-11-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('movie_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.theater')),
            ],
        ),
        migrations.AddField(
            model_name='bookmovie',
            name='show_time',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movieapp.showtime'),
        ),
    ]
