# Generated by Django 3.2.5 on 2023-11-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20231107_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmovie',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
